pipeline {  
	agent any
    
        stages { 
            stage("checkout") {  
           	    steps {  
              	    echo "git clone has started" 
                         checkout scmGit(branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[credentialsId: 'DevOps_Projects_2', url: 'https://github.com/Apurva14A/onlinebookstore.git']])
              	    echo "Repo is successfully cloned"  
              	    }  
         	    }
          		  stage("build") {  
           		    steps {  
              	 	   echo "build has started" 
                  	   sh "mvn clean install"
              	  	  echo "Build is successfully done"  

					}				  
				  
		
			    }
        }
}
